export type LoanType = "normal" | "vehicle" | "gold";
export type ExtraDeductionInput={name:string;amount:number};
export type CalculatorSettingsInput={interestPer10000For30Days:number;periodDays:number;normalPreDeductPeriods:number;specialPreDeductPeriods:number;vehicleFee:number;goldFixedLoanAmount:number;roundingMode:"round"};
export type CalculateInput={loanType:LoanType;loanAmount:number;periodCount:number;startDate:string;preDeductPeriods:number;goldDeduction?:number;extraDeductions:ExtraDeductionInput[];customerName?:string;};
export type PlanItem={periodIndex:number;dueDate:string;principalBefore:number;interestDue:number;paymentAmount:number;interestPaid:number;principalPaid:number;principalAfter:number;};
export type CalculationResult={loanAmount:number;periodCount:number;preDeductPeriods:number;interestAmount:number;vehicleFee:number;goldDeduction:number;otherDeductionsTotal:number;totalDeductions:number;actualReceivedAmount:number;fixedPaymentAmount:number;totalInterest:number;totalPayment:number;planItems:PlanItem[];};
export const defaultSettings={interestPer10000For30Days:750,periodDays:15,normalPreDeductPeriods:2,specialPreDeductPeriods:3,vehicleFee:2000,goldFixedLoanAmount:50000,roundingMode:"round"} as const;
export const money=(v:number)=>Number.isFinite(v)?Math.round(v):0;
export function addDays(d:string,days:number){const x=new Date(d+"T00:00:00");x.setDate(x.getDate()+days);return x.toISOString().slice(0,10)}
export function calcPeriodInterest(principal:number,s:CalculatorSettingsInput){return money(principal*(s.interestPer10000For30Days/10000)*(s.periodDays/30));}
export function calcPreDeductInterest(principal:number,periods:number,s:CalculatorSettingsInput){return money(calcPeriodInterest(principal,s)*periods)}
function buildAmortization(principal:number,periodCount:number,startDate:string,s:CalculatorSettingsInput){const r=(s.interestPer10000For30Days/10000)*(s.periodDays/30);const exactPayment=(principal*r*Math.pow(1+r,periodCount))/(Math.pow(1+r,periodCount)-1);const payment=money(exactPayment);const items=[];let remain=principal;let totalInterest=0;let totalPayment=0;for(let i=1;i<=periodCount;i++){const interest=money(remain*r);const last=i===periodCount;const pay=last?money(remain+interest):payment;const principalPaid=Math.min(remain,Math.max(pay-interest,0));const after=Math.max(remain-principalPaid,0);items.push({periodIndex:i,dueDate:addDays(startDate,s.periodDays*i),principalBefore:remain,interestDue:interest,paymentAmount:pay,interestPaid:interest,principalPaid,principalAfter:after});totalInterest+=interest;totalPayment+=pay;remain=after;}return{payment,totalInterest:money(totalInterest),totalPayment:money(totalPayment),items};}
export function findFixedPayment(principal:number,periodCount:number,startDate:string,s:CalculatorSettingsInput){const p=buildAmortization(principal,periodCount,startDate,s);return{payment:p.payment,items:p.items};}
export function calculateDebt(input:CalculateInput,s:CalculatorSettingsInput=defaultSettings){const loanAmount=input.loanType==="gold"?s.goldFixedLoanAmount:money(input.loanAmount);const interestAmount=calcPreDeductInterest(loanAmount,Math.max(0,Math.floor(input.preDeductPeriods)),s);const vehicleFee=input.loanType==="vehicle"?money(s.vehicleFee):0;const goldDeduction=input.loanType==="gold"?money(input.goldDeduction??0):0;const other=input.extraDeductions.reduce((a,b)=>a+money(b.amount),0);const totalDeductions=money(interestAmount+vehicleFee+goldDeduction+other);const actualReceivedAmount=money(loanAmount-totalDeductions);const plan=buildAmortization(loanAmount,Math.max(1,Math.floor(input.periodCount)),input.startDate,s);return{loanAmount,periodCount:Math.max(1,Math.floor(input.periodCount)),preDeductPeriods:Math.max(0,Math.floor(input.preDeductPeriods)),interestAmount,vehicleFee,goldDeduction,otherDeductionsTotal:other,totalDeductions,actualReceivedAmount,fixedPaymentAmount:plan.payment,totalInterest:plan.totalInterest,totalPayment:plan.totalPayment,planItems:plan.items};}
export function previewRepayment(principalRemaining:number,amount:number,s:CalculatorSettingsInput){const principalBefore=money(principalRemaining);const interestDue=calcPeriodInterest(principalBefore,s);const paid=money(amount);const interestPaid=Math.min(paid,interestDue);const principalPaid=Math.min(Math.max(paid-interestPaid,0),principalBefore);const principalAfter=Math.max(principalBefore-principalPaid,0);return{principalBefore,interestDue,interestPaid,principalPaid,principalAfter};}
