export type LoanType = "normal" | "vehicle" | "gold";
export type ExtraDeductionInput={name:string;amount:number};
export type CalculatorSettingsInput={interestPer10000For30Days:number;periodDays:number;normalPreDeductPeriods:number;specialPreDeductPeriods:number;vehicleFee:number;goldFixedLoanAmount:number;roundingMode:"round"};
export type CalculateInput={loanType:LoanType;loanAmount:number;periodCount:number;startDate:string;preDeductPeriods:number;goldDeduction?:number;extraDeductions:ExtraDeductionInput[];customerName?:string;};
export type PlanItem={periodIndex:number;dueDate:string;principalBefore:number;interestDue:number;paymentAmount:number;interestPaid:number;principalPaid:number;principalAfter:number;};
export type CalculationResult={loanAmount:number;periodCount:number;preDeductPeriods:number;interestAmount:number;vehicleFee:number;goldDeduction:number;otherDeductionsTotal:number;totalDeductions:number;actualReceivedAmount:number;fixedPaymentAmount:number;totalInterest:number;totalPayment:number;planItems:PlanItem[];};
export const defaultSettings={interestPer10000For30Days:750,periodDays:15,normalPreDeductPeriods:2,specialPreDeductPeriods:3,vehicleFee:2000,goldFixedLoanAmount:50000,roundingMode:"round"} as const;
export const money=(v:number)=>Number.isFinite(v)?Math.round(v):0;
export function getAutoPreDeductPeriods(dateText:string){const d=new Date(dateText+"T00:00:00").getDate();return(d>=29||d<=5)?3:2;}
export function addDays(d:string,days:number){const x=new Date(d+"T00:00:00");x.setDate(x.getDate()+days);return x.toISOString().slice(0,10)}
export function calcPeriodInterest(principal:number,s:CalculatorSettingsInput){return money(principal*(s.interestPer10000For30Days/10000)*(s.periodDays/30));}
export function calcPreDeductInterest(principal:number,periods:number,s:CalculatorSettingsInput){return money(calcPeriodInterest(principal,s)*periods)}
function buildAmortization(principal:number,periodCount:number,startDate:string,s:CalculatorSettingsInput){const r=(s.interestPer10000For30Days/10000)*(s.periodDays/30);const exact=(principal*r*Math.pow(1+r,periodCount))/(Math.pow(1+r,periodCount)-1);const payment=money(exact);const items=[];let remain=principal;let ti=0,tp=0;for(let i=1;i<=periodCount;i++){const interest=money(remain*r);const pay=i===periodCount?money(remain+interest):payment;const pp=Math.min(remain,Math.max(pay-interest,0));const after=Math.max(remain-pp,0);items.push({periodIndex:i,dueDate:addDays(startDate,s.periodDays*i),principalBefore:remain,interestDue:interest,paymentAmount:pay,interestPaid:interest,principalPaid:pp,principalAfter:after});ti+=interest;tp+=pay;remain=after;}return{payment,totalInterest:money(ti),totalPayment:money(tp),items};}
export function calculateDebt(input:CalculateInput,s:CalculatorSettingsInput=defaultSettings){const loanAmount=input.loanType==='gold'?s.goldFixedLoanAmount:money(input.loanAmount);const autoPeriods=input.preDeductPeriods>0?input.preDeductPeriods:getAutoPreDeductPeriods(input.startDate);const interestAmount=calcPreDeductInterest(loanAmount,autoPeriods,s);const vehicleFee=input.loanType==='vehicle'?money(s.vehicleFee):0;const goldDeduction=input.loanType==='gold'?money(input.goldDeduction??0):0;const other=input.extraDeductions.reduce((a,b)=>a+money(b.amount),0);const totalDeductions=money(interestAmount+vehicleFee+goldDeduction+other);const actualReceivedAmount=money(loanAmount-totalDeductions);const plan=buildAmortization(loanAmount,Math.max(1,Math.floor(input.periodCount)),input.startDate,s);return{loanAmount,periodCount:Math.max(1,Math.floor(input.periodCount)),preDeductPeriods:autoPeriods,interestAmount,vehicleFee,goldDeduction,otherDeductionsTotal:other,totalDeductions,actualReceivedAmount,fixedPaymentAmount:plan.payment,totalInterest:plan.totalInterest,totalPayment:plan.totalPayment,planItems:plan.items};}
export function previewRepayment(principalRemaining:number,amount:number,s:CalculatorSettingsInput,daysElapsed:number){const principalBefore=money(principalRemaining);const interestDue=money(principalBefore*(s.interestPer10000For30Days/10000)*(daysElapsed/30));const paid=money(amount);const interestPaid=Math.min(paid,interestDue);const principalPaid=Math.min(Math.max(paid-interestPaid,0),principalBefore);const principalAfter=Math.max(principalBefore-principalPaid,0);return{principalBefore,interestDue,interestPaid,principalPaid,principalAfter};}
